import {
  CHALLENGE_BASE64URL,
  KEY_VAULT_KEY_ID,
  KEY_VAULT_KEY_NAME,
  PUBLIC_KEY_CREDENTIAL_CREATION_OPTIONS,
  RP_ID,
  RP_ORIGIN,
  USER_ID,
  setDeep,
} from '@repo/core/__tests__/helpers';
import { upsertTestingUser } from '@repo/prisma/__tests__/helpers';

import { COSEKeyAlgorithm } from '@repo/keys/enums';
import { COSEKeyMapper } from '@repo/keys/mappers';
import { PrismaClient } from '@repo/prisma';
import {
  VerifiedRegistrationResponse,
  verifyRegistrationResponse,
  type RegistrationResponseJSON,
} from '@simplewebauthn/server';
import { Schema } from 'effect';
import { afterAll, beforeAll, describe, expect, test } from 'vitest';

import { UUIDMapper } from '../../../../core/src/mappers';
import { VirtualAuthenticator } from '../../../src/VirtualAuthenticator';
import { Attestation } from '../../../src/enums/Attestation';
import { PublicKeyCredentialType } from '../../../src/enums/PublicKeyCredentialType';
import { WebAuthnCredentialKeyMetaType } from '../../../src/enums/WebAuthnCredentialKeyMetaType';
import { AttestationNotSupported } from '../../../src/exceptions/AttestationNotSupported';
import { NoSupportedPubKeyCredParamFound } from '../../../src/exceptions/NoSupportedPubKeyCredParamWasFound';
import type { PublicKeyCredentialCreationOptions } from '../../../src/validation/PublicKeyCredentialCreationOptionsSchema';
import { PublicKeyCredentialSchema } from '../../../src/validation/PublicKeyCredentialSchema';
import { credentialSigner } from '../../helpers/credentialSigner';
import { COSEPublicKey, keyPair } from '../../helpers/key';

const prisma = new PrismaClient();

const createCredentialAndVerifyRegistrationResponse = async (opts: {
  authenticator: VirtualAuthenticator;
  publicKeyCredentialCreationOptions: PublicKeyCredentialCreationOptions;
}) => {
  const { authenticator, publicKeyCredentialCreationOptions } = opts;

  // Simulate the full WebAuthn registration ceremony.
  // This creates a new public key credential (passkey) using the
  // specified options, public key, and key vault metadata.
  const publicKeyCredential = await authenticator.createCredential({
    publicKeyCredentialCreationOptions,
    generateKeyPair: async () => ({
      COSEPublicKey: COSEKeyMapper.COSEKeyToBytes(COSEPublicKey),
      webAuthnCredentialKeyMetaType: WebAuthnCredentialKeyMetaType.KEY_VAULT,
      webAuthnCredentialKeyVaultKeyMeta: {
        keyVaultKeyId: KEY_VAULT_KEY_ID,
        keyVaultKeyName: KEY_VAULT_KEY_NAME,
        hsm: false,
      },
    }),
    signatureFactory: async ({ data }) => credentialSigner.sign(data),
    meta: {
      userId: USER_ID,
      origin: RP_ORIGIN,
    },
  });

  console.log(
    Schema.encodeSync(PublicKeyCredentialSchema)(publicKeyCredential),
  );

  // Verify the registration response generated by the authenticator.
  // This confirms the credential was created correctly according to
  // WebAuthn standards and our server's expectations (challenge, RP ID, etc.).
  const registrationVerification = await verifyRegistrationResponse({
    response: Schema.encodeSync(PublicKeyCredentialSchema)(
      publicKeyCredential,
    ) as RegistrationResponseJSON,
    expectedChallenge: CHALLENGE_BASE64URL,
    expectedOrigin: RP_ORIGIN,
    expectedRPID: RP_ID,
    requireUserVerification: true, // Authenticator does perform UV
    requireUserPresence: false, // Authenticator does NOT perform UP
  });

  const webAuthnCredentialId = UUIDMapper.bytesToUUID(
    publicKeyCredential.rawId,
  );

  return {
    publicKeyCredential,
    registrationVerification,
    webAuthnCredentialId,
  };
};

const cleanup = async () => {
  await prisma.$transaction([
    prisma.user.deleteMany(),
    prisma.webAuthnCredential.deleteMany(),
    prisma.webAuthnCredentialKeyVaultKeyMeta.deleteMany(),
  ]);
};

describe('VirtualAuthenticator.createCredential()', () => {
  const authenticator = new VirtualAuthenticator({ prisma });

  describe('PublicKeyCredentialCreationOptions.attestation', () => {
    describe.each([
      {
        attestation: undefined,
      } satisfies Partial<PublicKeyCredentialCreationOptions>,
      {
        attestation: Attestation.NONE,
      } satisfies Partial<PublicKeyCredentialCreationOptions>,
      {
        attestation: Attestation.DIRECT,
      } satisfies Partial<PublicKeyCredentialCreationOptions>,
    ])('With attestation $attestation', ({ attestation }) => {
      let registrationVerification: VerifiedRegistrationResponse;
      let webAuthnCredentialId: string;

      const publicKeyCredentialCreationOptions = {
        ...PUBLIC_KEY_CREDENTIAL_CREATION_OPTIONS,
        attestation,
      } satisfies PublicKeyCredentialCreationOptions;

      beforeAll(async () => {
        await cleanup();
        await upsertTestingUser({ prisma });

        ({ registrationVerification, webAuthnCredentialId } =
          await createCredentialAndVerifyRegistrationResponse({
            authenticator,
            publicKeyCredentialCreationOptions,
          }));
      });

      afterAll(async () => {
        await cleanup();
      });

      test('Should return a verified registration', () => {
        expect(registrationVerification.verified).toBe(true);
      });

      test('Should have a counter of 0', () => {
        expect(
          registrationVerification.registrationInfo?.credential.counter,
        ).toBe(0);
      });

      test('Should have the correct public key', () => {
        const jwk = COSEKeyMapper.COSEKeyToJwk(
          COSEKeyMapper.bytesToCOSEKey(
            registrationVerification.registrationInfo!.credential.publicKey,
          ),
        );
        expect(jwk).toMatchObject(keyPair.publicKey.export({ format: 'jwk' }));
      });

      test('Should save the WebAuthnCredential to the database', async () => {
        const webAuthnCredential = await prisma.webAuthnCredential.findUnique({
          where: {
            id: webAuthnCredentialId,
          },
        });

        expect(webAuthnCredential).not.toBeNull();
        expect(webAuthnCredential).toMatchObject({
          id: webAuthnCredentialId,
          userId: USER_ID,
        });
      });

      test('Should save the KeyVaultKeyMeta to the database', async () => {
        const keyMeta =
          await prisma.webAuthnCredentialKeyVaultKeyMeta.findFirst({
            where: {
              webAuthnCredentialId: webAuthnCredentialId,
            },
          });

        expect(keyMeta).not.toBeNull();
        expect(keyMeta).toMatchObject({
          webAuthnCredentialId: webAuthnCredentialId,
          keyVaultKeyId: KEY_VAULT_KEY_ID,
          keyVaultKeyName: KEY_VAULT_KEY_NAME,
          hsm: false,
        });
      });
    });

    test.each([
      {
        attestation: Attestation.ENTERPRISE,
      } satisfies Partial<PublicKeyCredentialCreationOptions>,
      {
        attestation: Attestation.INDIRECT,
      } satisfies Partial<PublicKeyCredentialCreationOptions>,
    ])(
      `Should throw ${AttestationNotSupported.name} with attestation $attestation`,
      async ({ attestation }) => {
        await expect(async () =>
          createCredentialAndVerifyRegistrationResponse({
            authenticator,
            publicKeyCredentialCreationOptions: setDeep(
              PUBLIC_KEY_CREDENTIAL_CREATION_OPTIONS,
              'attestation',
              () => attestation,
            ),
          }),
        ).rejects.toThrowError(
          new AttestationNotSupported({ data: { attestation } }),
        );
      },
    );

    test('Shold throw type mismatch when attestation is not in enum', async () => {
      const publicKeyCredentialCreationOptions = {
        ...PUBLIC_KEY_CREDENTIAL_CREATION_OPTIONS,
        attestation: 'WRONG_ATTESTATION',
      };

      await expect(async () =>
        createCredentialAndVerifyRegistrationResponse({
          authenticator,
          publicKeyCredentialCreationOptions:
            publicKeyCredentialCreationOptions as PublicKeyCredentialCreationOptions,
        }),
      ).rejects.toThrowError();
    });
  });

  describe('PublicKeyCredentialCreationOptions.pubKeyCredParams', () => {
    test('Should throw type mismatch when pubKeyCredParams is empty', async () => {
      const publicKeyCredentialCreationOptions = {
        ...PUBLIC_KEY_CREDENTIAL_CREATION_OPTIONS,
        pubKeyCredParams: [],
      };

      await expect(async () =>
        createCredentialAndVerifyRegistrationResponse({
          authenticator,
          publicKeyCredentialCreationOptions,
        }),
      ).rejects.toThrowError();
    });

    test.each([
      {
        pubKeyCredParams: [{ type: 'WRONG_TYPE', alg: COSEKeyAlgorithm.ES256 }],
      } satisfies Partial<PublicKeyCredentialCreationOptions>,
      {
        pubKeyCredParams: [
          {
            type: PublicKeyCredentialType.PUBLIC_KEY,
            alg: -8,
          },
        ],
      } satisfies Partial<PublicKeyCredentialCreationOptions>,
      {
        pubKeyCredParams: [
          {
            type: PublicKeyCredentialType.PUBLIC_KEY,
            alg: -8,
          },
          {
            type: 'WRONG_TYPE',
            alg: COSEKeyAlgorithm.ES256,
          },
        ],
      } satisfies Partial<PublicKeyCredentialCreationOptions>,
    ])(
      'Should throw with any supported pubKeyCredParams',
      async ({ pubKeyCredParams }) => {
        const publicKeyCredentialCreationOptions = {
          ...PUBLIC_KEY_CREDENTIAL_CREATION_OPTIONS,
          pubKeyCredParams,
          attestation: undefined,
        };

        await expect(async () =>
          createCredentialAndVerifyRegistrationResponse({
            authenticator,
            publicKeyCredentialCreationOptions,
          }),
        ).rejects.toThrowError(new NoSupportedPubKeyCredParamFound());
      },
    );
  });

  describe('meta.userId', () => {
    test('Should throw type mismatch when userId is invalid', async () => {
      await expect(async () =>
        authenticator.createCredential({
          publicKeyCredentialCreationOptions:
            PUBLIC_KEY_CREDENTIAL_CREATION_OPTIONS,
          generateKeyPair: async () => ({
            COSEPublicKey: COSEKeyMapper.COSEKeyToBytes(COSEPublicKey),
            webAuthnCredentialKeyMetaType:
              WebAuthnCredentialKeyMetaType.KEY_VAULT,
            webAuthnCredentialKeyVaultKeyMeta: {
              keyVaultKeyId: KEY_VAULT_KEY_ID,
              keyVaultKeyName: KEY_VAULT_KEY_NAME,
              hsm: false,
            },
          }),
          signatureFactory: async ({ data }) => credentialSigner.sign(data),
          meta: {
            userId: 'INVALID_USER_ID',
            origin: RP_ORIGIN,
          },
        }),
      ).to.rejects.toThrowError();
    });
  });
});
