import { USER_ID } from '../../../auth/__tests__/helpers';

import { UUIDMapper } from '@repo/core/mappers';
import {
  RegistrationResponseJSON,
  VerifiedRegistrationResponse,
  verifyRegistrationResponse,
} from '@simplewebauthn/server';

import { PublicKeyCredentialDtoSchema } from '../../../contract/src/dto/credentials/components/PublicKeyCredentialDtoSchema';
import { VirtualAuthenticatorAgent } from '../../src/VirtualAuthenticatorAgent';
import {
  PublicKeyCredential,
  PublicKeyCredentialCreationOptions,
} from '../../src/zod-validation';
import { AuthenticatorAgentContextArgs } from '../../src/zod-validation/AuthenticatorAgentContextArgsSchema';
import { AuthenticatorAgentMetaArgs } from '../../src/zod-validation/AuthenticatorAgentMetaArgsSchema';
import { RP_ID, RP_ORIGIN } from './consts';

export type PerformPublicKeyCredentialRegistrationAndVerifyArgs = {
  agent: VirtualAuthenticatorAgent;

  publicKeyCredentialCreationOptions: PublicKeyCredentialCreationOptions;
  meta?: Partial<AuthenticatorAgentMetaArgs>;
  context?: Partial<AuthenticatorAgentContextArgs>;

  requireUserVerification?: boolean;
  requireUserPresence?: boolean;
};

export type PerformPublicKeyCredentialRegistrationAndVerifyResult = {
  publicKeyCredential: PublicKeyCredential;
  registrationVerification: VerifiedRegistrationResponse;
  webAuthnCredentialId: string;
};

export const performPublicKeyCredentialRegistrationAndVerify = async (
  opts: PerformPublicKeyCredentialRegistrationAndVerifyArgs,
): Promise<PerformPublicKeyCredentialRegistrationAndVerifyResult> => {
  const {
    agent,

    publicKeyCredentialCreationOptions,
    meta,
    context,

    requireUserVerification,
    requireUserPresence,
  } = opts;

  // Simulate the full WebAuthn registration ceremony.
  // This creates a new public key credential (passkey) using the
  // specified options, public key, and key vault metadata.
  const publicKeyCredential = await agent.createCredential({
    origin: RP_ORIGIN,
    options: {
      publicKey: publicKeyCredentialCreationOptions,
    },
    sameOriginWithAncestors: true,

    // Internal options
    meta: {
      userId: USER_ID,
      origin: RP_ORIGIN,
      ...meta,
    },
    context: {
      apiKeyId: null,
      ...context,
    },
  });

  // Verify the registration response generated by the authenticator.
  // This confirms the credential was created correctly according to
  // WebAuthn standards and our server's expectations (challenge, RP ID, etc.).
  const registrationVerification = await verifyRegistrationResponse({
    response: PublicKeyCredentialDtoSchema.encode(
      publicKeyCredential,
    ) as RegistrationResponseJSON,
    expectedChallenge: Buffer.from(
      publicKeyCredentialCreationOptions.challenge,
    ).toString('base64url'),
    expectedOrigin: RP_ORIGIN,
    expectedRPID: RP_ID,
    requireUserVerification:
      requireUserVerification ??
      publicKeyCredentialCreationOptions.authenticatorSelection
        ?.userVerification === 'required',
    requireUserPresence: requireUserPresence ?? true,
  });

  const webAuthnCredentialId = UUIDMapper.bytesToUUID(
    publicKeyCredential.rawId,
  );

  return {
    publicKeyCredential,
    registrationVerification,
    webAuthnCredentialId,
  };
};
