import { USER_ID } from '../../../auth/__tests__/helpers';

import { UUIDMapper } from '@repo/core/mappers';
import {
  RegistrationResponseJSON,
  VerifiedRegistrationResponse,
  verifyRegistrationResponse,
} from '@simplewebauthn/server';

import { PublicKeyCredentialDtoSchema } from '../../../contract/src/dto/credentials/components/PublicKeyCredentialDtoSchema';
import { VirtualAuthenticator } from '../../src/VirtualAuthenticator';
import {
  PublicKeyCredential,
  PublicKeyCredentialCreationOptions,
} from '../../src/zod-validation';
import { RP_ID, RP_ORIGIN } from './consts';

export type PerformPublicKeyCredentialRegistrationAndVerifyArgs = {
  authenticator: VirtualAuthenticator;
  publicKeyCredentialCreationOptions: PublicKeyCredentialCreationOptions;
  requireUserVerification?: boolean;
  requireUserPresence?: boolean;
};

export type PerformPublicKeyCredentialRegistrationAndVerifyResult = {
  publicKeyCredential: PublicKeyCredential;
  registrationVerification: VerifiedRegistrationResponse;
  webAuthnCredentialId: string;
};

export const performPublicKeyCredentialRegistrationAndVerify = async (opts: {
  authenticator: VirtualAuthenticator;
  publicKeyCredentialCreationOptions: PublicKeyCredentialCreationOptions;
  requireUserVerification?: boolean;
  requireUserPresence?: boolean;
}): Promise<PerformPublicKeyCredentialRegistrationAndVerifyResult> => {
  const {
    authenticator,
    publicKeyCredentialCreationOptions,
    requireUserVerification,
    requireUserPresence,
  } = opts;

  // Simulate the full WebAuthn registration ceremony.
  // This creates a new public key credential (passkey) using the
  // specified options, public key, and key vault metadata.
  const publicKeyCredential = await authenticator.createCredential({
    publicKeyCredentialCreationOptions,
    meta: {
      userId: USER_ID,
      origin: RP_ORIGIN,
    },
    context: {
      apiKeyId: null,
    },
  });

  // Verify the registration response generated by the authenticator.
  // This confirms the credential was created correctly according to
  // WebAuthn standards and our server's expectations (challenge, RP ID, etc.).
  const registrationVerification = await verifyRegistrationResponse({
    response: PublicKeyCredentialDtoSchema.encode(
      publicKeyCredential,
    ) as RegistrationResponseJSON,
    expectedChallenge: Buffer.from(
      publicKeyCredentialCreationOptions.challenge,
    ).toString('base64url'),
    expectedOrigin: RP_ORIGIN,
    expectedRPID: RP_ID,
    requireUserVerification: requireUserVerification ?? true,
    requireUserPresence: requireUserPresence ?? true,
  });

  const webAuthnCredentialId = UUIDMapper.bytesToUUID(
    publicKeyCredential.rawId,
  );

  return {
    publicKeyCredential,
    registrationVerification,
    webAuthnCredentialId,
  };
};
