services:
  # console:
  #   build:
  #     context: .
  #     dockerfile: ./apps/console/Dockerfile
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - postgres
  #     - lowkey-vault
  #     - assumed-identity
  # hono:
  #   build:
  #     context: .
  #     dockerfile: ./apps/hono/Dockerfile
  #   ports:
  #     - '3001:3001'
  #   depends_on:
  #     - postgres
  #     - lowkey-vault
  #     - assumed-identity
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  lowkey-vault:
    container_name: lowkey-vault
    image: nagyesta/lowkey-vault:4.0.27@sha256:1edfe3f23c057aabf1cc5078a740d5130bdf795b00a66aac1d29faf859251f69
    ports:
      - '3443:3443'
    volumes:
      - lowkey-vault-import:/import/:rw
      - lowkey-vault-config:/config/:ro
    environment:
      # Set arguments for Lowkey Vault configuring key parameters, such as:
      # - setting the port we want to use: --server.port=3443
      # - overriding the key store type: --server.ssl.key-store-type=JKS
      # - overriding the key store path: --server.ssl.key-store=/config/cert.jks
      # - overriding the key store password: --server.ssl.key-store-password=password
      # - disable automatic vault creation: --LOWKEY_VAULT_NAMES=-
      # - turn off debug option controlling request logging: --LOWKEY_DEBUG_REQUEST_LOG=false
      # - specify the name of the import file: --LOWKEY_IMPORT_LOCATION=/import/keyvault.json.hbs
      # - defining the value of {{host}} placeholders in the import: --LOWKEY_IMPORT_TEMPLATE_HOST=localhost
      # - defining the value of {{port}} placeholders in the import: --LOWKEY_IMPORT_TEMPLATE_PORT=8443
      # More details at: https://github.com/nagyesta/lowkey-vault/tree/main/lowkey-vault-app#startup-parameters
      LOWKEY_ARGS: >
        --server.port=3443
        --server.ssl.key-store-type=JKS
        --server.ssl.key-store=/config/cert.jks
        --server.ssl.key-store-password=password
        --LOWKEY_VAULT_NAMES=-
        --LOWKEY_DEBUG_REQUEST_LOG=true
        --LOWKEY_IMPORT_LOCATION=/import/keyvault.json.hbs
        --LOWKEY_IMPORT_TEMPLATE_HOST=localhost
        --LOWKEY_IMPORT_TEMPLATE_PORT=3443
  assumed-identity:
    container_name: assumed-identity
    image: nagyesta/assumed-identity:2.1.17@sha256:60cd8ada7450238a9b1d82848fc2cfbe5499f68afd9b99b3a594f24b60a61044
    ports:
      - '3080:3080'
    environment:
      # Set port number to the one we want to use on the host machine
      ASSUMED_ID_PORT: '3080'
volumes:
  lowkey-vault-import:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$PWD/.lowkey-vault/import'
  lowkey-vault-config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$PWD/.lowkey-vault/config'
