import { VirtualAuthenticatorAgentCredentialSelectInterruptionPayloadSchema } from '../../validation/authenticatorAgent/interruption/VirtualAuthenticatorAgentCredentialSelectInterruptionPayloadSchema';

export const VirtualAuthenticatorAgentCredentialSelectInterruptionPayloadDtoSchema =
  VirtualAuthenticatorAgentCredentialSelectInterruptionPayloadSchema;
