import { USER_ID } from '@repo/auth/__tests__/helpers';

import { UUIDMapper } from '@repo/core/mappers';
import { toB64 } from '@repo/utils';
import {
  type RegistrationResponseJSON,
  verifyRegistrationResponse,
} from '@simplewebauthn/server';
import { expect } from 'vitest';

import { VirtualAuthenticatorAgent } from '../../src/VirtualAuthenticatorAgent';
import { UserPresenceRequiredAgentException } from '../../src/exceptions/UserPresenceRequiredAgentException';
import { UserVerificationRequiredAgentException } from '../../src/exceptions/UserVerificationRequiredAgentException';
import { decodeAttestationObject } from '@repo/virtual-authenticator/cbor';
import { parseAuthenticatorData } from '@repo/virtual-authenticator/cbor';
import { PublicKeyCredentialDtoSchema } from '@repo/virtual-authenticator/dto';
import { UserVerification } from '@repo/virtual-authenticator/enums';
import { VirtualAuthenticatorUserVerificationType } from '@repo/virtual-authenticator/enums';
import type { RegistrationState } from '@repo/virtual-authenticator/state';
import { StateManager } from '@repo/virtual-authenticator/state';
import type { AuthenticatorAgentMetaArgs } from '../../src/validation/AuthenticatorAgentMetaArgsSchema';
import type { PublicKeyCredentialCreationOptions } from '@repo/virtual-authenticator/validation';
import type { PublicKeyCredential } from '@repo/virtual-authenticator/validation';
import { RP_ORIGIN, VIRTUAL_AUTHENTICATOR_ID } from '@repo/virtual-authenticator/__tests__/helpers';

export type PerformPublicKeyCredentialRegistrationAndVerifyArgs = {
  stateManager: StateManager;
  agent: VirtualAuthenticatorAgent;
  publicKeyCredentialCreationOptions: PublicKeyCredentialCreationOptions;
  meta?: Partial<AuthenticatorAgentMetaArgs>;
  uvState?: { pin?: string };
};

export const performPublicKeyCredentialRegistrationAndVerify = async (
  opts: PerformPublicKeyCredentialRegistrationAndVerifyArgs,
) => {
  const {
    agent,
    publicKeyCredentialCreationOptions,
    meta: metaOptions = {},
    uvState = { pin: undefined },
  } = opts;

  const meta: AuthenticatorAgentMetaArgs = {
    userId: USER_ID,
    virtualAuthenticatorId: VIRTUAL_AUTHENTICATOR_ID,
    apiKeyId: null,
    origin: RP_ORIGIN,

    userPresenceEnabled: true,
    userVerificationEnabled: true,
    userVerificationType: VirtualAuthenticatorUserVerificationType.NONE,
    ...metaOptions,
  };

  const expectedRPID =
    publicKeyCredentialCreationOptions?.rp?.id ?? new URL(meta.origin).hostname;

  // Simulate the full WebAuthn registration ceremony.
  // This creates a new public key credential (passkey) using the
  // specified options, public key, and key vault metadata.
  // Simulate the full WebAuthn registration ceremony.
  let retries = -1;
  let publicKeyCredential: PublicKeyCredential | undefined;
  let prevStateToken: string | undefined;
  let nextState: RegistrationState = {};

  while (!publicKeyCredential) {
    retries++;
    try {
      publicKeyCredential = await agent.createCredential({
        origin: meta.origin,
        options: {
          publicKey: publicKeyCredentialCreationOptions,
        },
        sameOriginWithAncestors: true,

        // Internal options
        meta,
        prevStateToken,
        nextState,
      });
    } catch (error) {
      if (error instanceof UserPresenceRequiredAgentException) {
        prevStateToken = error.data.stateToken;

        nextState = {
          ...nextState,
          up: true,
        };
      } else if (error instanceof UserVerificationRequiredAgentException) {
        prevStateToken = error.data.stateToken;

        nextState = {
          ...nextState,
          uv: uvState,
        };
      } else {
        throw error;
      }
    }
  }

  if (!publicKeyCredential) {
    throw new Error('Failed to create credential.');
  }

  // Verify the registration response generated by the authenticator.
  // This confirms the credential was created correctly according to
  // WebAuthn standards and our server's expectations (challenge, RP ID, etc.).
  const registrationVerification = await verifyRegistrationResponse({
    response: PublicKeyCredentialDtoSchema.encode(
      publicKeyCredential,
    ) as RegistrationResponseJSON,
    expectedChallenge: toB64(publicKeyCredentialCreationOptions.challenge),
    expectedOrigin: meta.origin,
    expectedRPID,
    requireUserVerification:
      publicKeyCredentialCreationOptions.authenticatorSelection
        ?.userVerification === UserVerification.REQUIRED,
    requireUserPresence: true,
  });

  expect(registrationVerification.verified).toBe(true);

  const attestationObjectMap = decodeAttestationObject(
    registrationVerification.registrationInfo!.attestationObject,
  );

  const authData = attestationObjectMap.get('authData');

  const parsedAuthenticatorData = parseAuthenticatorData(authData);

  expect(parsedAuthenticatorData.extensionsData).toBe(undefined);

  // New credential counter should be always 0
  expect(parsedAuthenticatorData.counter).toBe(0);

  expect(parsedAuthenticatorData.flags.up).toBe(true);
  expect(parsedAuthenticatorData.flags.be).toBe(true);
  expect(parsedAuthenticatorData.flags.bs).toBe(true);

  expect(registrationVerification.registrationInfo!.credential).toBeDefined();

  const credentialUuid = UUIDMapper.bytesToUUID(publicKeyCredential.rawId);

  return {
    webAuthnCredential: registrationVerification.registrationInfo!.credential,
    publicKeyCredential,
    credentialUuid,
    registrationVerification,
    parsedAuthenticatorData,
    attestationObjectMap,
    retries,
  };
};
