import { AttestationSchema } from '@repo/enums';
import z from 'zod';

import { see } from '../meta/see.js';
import { Base64URLBufferSchema } from '../transformers/Base64URLBufferSchema.js';
import { AuthenticatorSelectionCriteriaSchema } from './AuthenticatorSelectionCriteriaSchema.js';
import { PublicKeyCredentialDescriptorSchema } from './PublicKeyCredentialDescriptorSchema.js';
import { PublicKeyCredentialParametersSchema } from './PublicKeyCredentialParametersSchema.js';
import { PublicKeyCredentialRpEntitySchema } from './PublicKeyCredentialRpEntitySchema.js';

/**
 * Zod schema for WebAuthn's PublicKeyCredentialCreationOptions.
 * This is sent from the server to the client to initiate passkey registration.
 *
 * @see https://www.w3.org/TR/webauthn/#dictdef-publickeycredentialcreationoptions
 */
export const PublicKeyCredentialCreationOptionsSchema = z
  .object({
    rp: PublicKeyCredentialRpEntitySchema,
    /**
     * Standard schema: `PublicKeyCredentialUserEntitySchema`
     * The user is infered from the authenticated user data
     */
    user: z.undefined().optional(),
    challenge: Base64URLBufferSchema.meta({
      description: 'A random string generated by the server.',
    }),
    pubKeyCredParams: z.array(PublicKeyCredentialParametersSchema),
    timeout: z.number().optional(),
    excludeCredentials: z.array(PublicKeyCredentialDescriptorSchema).optional(),
    authenticatorSelection: AuthenticatorSelectionCriteriaSchema.optional(),
    attestation: AttestationSchema.optional(),
    // Extensions can be complex; a generic record is often sufficient for validation
    extensions: z.record(z.string(), z.unknown()).optional(),
  })
  .meta({
    id: 'PublicKeyCredentialCreationOptions',
    description: `Options for creating a new public key credential. ${see(
      'https://www.w3.org/TR/webauthn/#dictdef-publickeycredentialcreationoptions',
    )}`,
  });

export type PublicKeyCredentialCreationOptions = z.infer<
  typeof PublicKeyCredentialCreationOptionsSchema
>;
