import type { ValueOfEnum } from '@repo/types';
import z from 'zod';

/**
 * The attestation statement format, which identifies the type of
 * attestation used by the authenticator.
 *
 * @see https://w3c.github.io/webauthn/#sctn-attestation-formats
 */
export const Fmt = {
  /**
   * Used for no attestation. This is a privacy-preserving option where
   * the Relying Party does not receive any verifiable information
   * about the authenticator.
   */
  NONE: 'none',
  /**
   * The most common format. Used for FIDO2 authenticators that don't
   * have a more specific format. This can represent both full
   * attestation (with a certificate chain) or "self-attestation"
   * (where the key signs itself).
   */
  PACKED: 'packed',
  /**
   * Used when the attestation signature is generated by a
   * Trusted Platform Module (TPM). This is common for
   * platform authenticators like Windows Hello.
   */
  TPM: 'tpm',
  /**
   * Used for attestation from the Android Keystore, which provides
   * hardware-backed key generation and storage.
   */
  ANDROID_KEY: 'android-key',
  /**
   * A legacy format for attestation using the Android SafetyNet API.
   * New implementations should prefer 'android-key'.
   */
  ANDROID_SAFETYNET: 'android-safetynet',
  /**
   * A legacy format for authenticators that are backwards-compatible
   * with the older FIDO U2F protocol.
   */
  FIDO_U2F: 'fido-u2f',
  /**
   * Used by Apple platform authenticators (e.g., Touch ID, Face ID)
   * to provide an anonymous, hardware-backed attestation from
   * the Secure Enclave.
   */
  APPLE_ANONYMOUS: 'apple-anonymous',
} as const;

export type Fmt = ValueOfEnum<typeof Fmt>;

export const FmtSchema = z
  .enum([
    Fmt.NONE,
    Fmt.PACKED,
    Fmt.TPM,
    Fmt.ANDROID_KEY,
    Fmt.ANDROID_SAFETYNET,
    Fmt.FIDO_U2F,
    Fmt.APPLE_ANONYMOUS,
  ])
  .meta({
    description: 'Attestation Statement Format',
    examples: [Fmt.NONE, Fmt.PACKED],
  });
