openapi: 3.1.0
info:
  title: API
  version: 1.0.0
paths:
  /credentials:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticatorAssertionResponse"
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                description: The JSON payload for a registration verification.
                type: object
                properties:
                  clientDataJSON:
                    $ref: "#/components/schemas/Base64URL"
                  attestationObject:
                    $ref: "#/components/schemas/Base64URL"
                required:
                  - clientDataJSON
                  - attestationObject
                additionalProperties: false
components:
  schemas:
    AuthenticatorAssertionResponse:
      description: The JSON payload for an authentication verification.
      type: object
      properties:
        clientDataJSON:
          $ref: "#/components/schemas/Base64URL"
        authenticatorData:
          $ref: "#/components/schemas/Base64URL"
        signature:
          $ref: "#/components/schemas/Base64URL"
        userHandle:
          anyOf:
            - $ref: "#/components/schemas/Base64URL"
            - type: "null"
      required:
        - clientDataJSON
        - authenticatorData
        - signature
        - userHandle
      additionalProperties: false
    Base64URL:
      description: A Base64URL-encoded string, which will be decoded into a Buffer.
      examples:
        - aGVsbG8gd29ybGQ
      type: string
