import type { ValueOfEnum } from '@repo/types';
import z from 'zod';

import { HTTPStatusCode } from './HTTPStatusCode';

export const HTTPExceptionCode = {
  ...HTTPStatusCode,
  REQUEST_VALIDATION_FAILED: 'REQUEST_VALIDATION_FAILED',

  API_KEY_NOT_FOUND: 'API_KEY_NOT_FOUND',
  API_KEY_REVOKE_FAILED: 'API_KEY_REVOKE_FAILED',
  INVALID_API_KEY: 'INVALID_API_KEY',
  API_KEY_DELETE_FAILED: 'API_KEY_DELETE_FAILED',
  API_KEY_DELETE_ENABLED_FAILED: 'API_KEY_DELETE_ENABLED_FAILED',

  CREDENTIAL_NOT_FOUND: 'CREDENTIAL_NOT_FOUND',
  NO_SUPPORTED_PUB_KEY_CRED_PARAM_WAS_FOUND:
    'NO_SUPPORTED_PUB_KEY_CRED_PARAM_WAS_FOUND',

  CANNOT_PARSE_JSON_WEB_KEY: 'CANNOT_PARSE_JSON_WEB_KEY',
  CANNOT_PARSE_COSE_KEY: 'CANNOT_PARSE_COSE_KEY',

  UNSUPPORTED_KTY: 'UNSUPPORTED_KTY',
} as const;

export type HTTPExceptionCode = ValueOfEnum<typeof HTTPExceptionCode>;

export const HTTPExceptionCodeSchema = z.enum(HTTPExceptionCode).meta({
  description: 'API error',
  examples: [HTTPExceptionCode.UNAUTHORIZED],
});
